name: zig-test

env:
  ZIG_VERSION: 0.14.0

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.zig"
      - "src/*.zig"
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zig-test:
    name: zig test
    runs-on: ubuntu-latest

    steps:
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: zig build test
